METADATA_TYPE_DICT = {
            0: ['b'],
            1: ['varint'],
            2: ['f'],
            3: ['b','s'],
            4: ['chat'],
            5: ['?', 'chat'],
            6: ['slot'],
            7: ['?'],
            8: ['f', 'f', 'f'],
            9: ['position'],
            10: ['?', 'position'],
            11: ['varint'],
            12: ['?', 'uuid'],
            13: ['?', 'varint'],
            14: ['nbt'],
            15: ['particle'],
            16: ['varint', 'varint', 'varint'],
            17: ['?', 'varint'],
            18: ['pose']
}